language: csharp
solution: ./src/StrangerData.sln

install:
  - nuget restore ./src/StrangerData.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ./src/StrangerData.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./StrangerData.UnitTests/bin/Release/StrangerData.UnitTests.dll
