on:
  pull_request:

jobs:
  analisys:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          project: ['StrangerData', 'card-interview', 'demo-sdk-android', 'go-coveralls-api', 'superbowleto']
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'true'
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v4
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            LC_ALL: "pr_BR.UTF-8"
          with:
            projectBaseDir: project/${{ matrix.project }}
            args: >
              --define sonar.projectKey=${{ matrix.project }}
              --define sonar.organization=pastelbinario
        - name: Check for duplicate code
          uses: platisd/duplicate-code-detection-tool@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            directories: "project/${{ matrix.project }}/"
        - name: Pull MegaLinter
          run: docker pull oxsecurity/megalinter:v8
        - name: Run MegaLinter for Project ${{ matrix.project }}
          run: |
            docker run --rm -v $(pwd)/project/${{ matrix.project }}:/tmp/lint oxsecurity/megalinter:v8
        - uses: coderabbitai/ai-pr-reviewer@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          with:
            debug: false
            review_simple_changes: false
            review_comment_lgtm: false
          

  multi-tool:
      runs-on: ubuntu-latest
      steps:
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: btfshadow/quality-tools-test